module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since:
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji:
        subtitle:
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        headingAnchor: false
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client/props.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

    customjscssraw:
    - "<canvas class="fireworks" style="position:fixed;left:0;top:0;z-index:99999999;pointer-events:none;"></canvas>"
    - "<script type="text/javascript" src="https://files.cnblogs.com/files/songhaixing/anime.min.js"></script>"
    - "<script type="text/javascript" src="https://files.cnblogs.com/files/songhaixing/fireworks.js"></script>"
    - "<link href="https://cdn.bootcss.com/aplayer/1.10.1/APlayer.min.css" rel="stylesheet">"
    - "<script src="https://cdn.bootcss.com/aplayer/1.10.1/APlayer.min.js"></script>"
    - "<script src="https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js"></script>"
    - >
        <div id="aplayer01"></div>
<script type="text/javascript">
    const ap = new APlayer({
　　　　  //定义容器
        container: document.getElementById('aplayer01'),
　　　　 //关于音频的相关参数：
        audio: [{
            name: 'とおりゃんせ～甘美風来 (通行歌～甘美风来) (Inst_)',//音频名称
            artist: 'Famishin',//艺术家
            url: 'https://resources.blog.kihh.xyz/file/Famishin%20-%20%E3%81%A8%E3%81%8A%E3%82%8A%E3%82%83%E3%82%93%E3%81%9B%EF%BD%9E%E7%94%98%E7%BE%8E%E9%A2%A8%E6%9D%A5%20(%E9%80%9A%E8%A1%8C%E6%AD%8C%EF%BD%9E%E7%94%98%E7%BE%8E%E9%A3%8E%E6%9D%A5)%20(Inst_).flac',//文件地址
            cover: 'https://y.qq.com/music/photo_new/T002R300x300M000004StPJJ03g0cR_1.jpg?max_age=2592000'//封面地址
        }]
    });
</script>